swagger: '2.0'
info:
  version: '0.1'
  title: opspec node api
consumes:
  - application/json
produces:
  - application/json
  - text/plain
paths:
  /event-stream:
    get:
      summary: Get event stream
      description: |
        The connection will be upgraded to use the websocket protocol.
        Inspired by Docker Remote API [GET /events endpoint](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/monitor-dockers-events)
      parameters:
        - name: filter
          in: query
          description: |
            A json encoded object supporting the following:

            |attribute|type|description|
            |--|--|--|
            |opGraphIds|array of strings|events must have one of these op graph ids|
          required: false
          type: string
          format: json
      tags:
        - event-stream
      responses:
        '101':
          description: Switching Protocols
          headers:
            Upgrade:
              type: string
              enum:
                - websocket
            Connection:
              type: string
              enum:
                - Upgrade
          schema:
            type: array
            items:
              $ref: '#/definitions/Event'
        '400':
          description: Bad Request
          schema:
            type: string
  /liveness:
    get:
      summary: Get liveness of node
      tags:
        - liveness
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /op-runs:
    post:
      summary: Run op
      tags:
        - op-runs
      parameters:
        - name: body
          in: body
          description: The body of the request
          schema:
            title: RunOpReq
            type: object
            required:
              - opRef
            properties:
              args:
                type: object
                additionalProperties:
                  $ref: '#/definitions/OpRunArg'
              opRef:
                type: string
      responses:
        '201':
          description: Created
          headers:
            Correlation-Id:
              type: string
          schema:
            description: The id of the op graph
            type: string
        '400':
          description: Bad Request
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
  /op-run-kills:
    post:
      summary: Kill op run
      tags:
        - op-run-kills
      parameters:
        - name: body
          in: body
          description: The body of the request
          required: true
          schema:
            title: KillOpRunReq
            type: object
            required:
              - opRunId
            properties:
              opRunId:
                type: string
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
definitions:
  Event:
    type: object
    properties:
      timestamp:
        type: string
        format: dateTime
      # @TODO: use oneOf as soon as OpenAPI v3 is released
      containerExited:
        $ref: '#/definitions/ContainerExitedEvent'
      containerStarted:
        $ref: '#/definitions/ContainerStartedEvent'
      containerStdErrWrittenTo:
        $ref: '#/definitions/ContainerStdErrWrittenToEvent'
      containerStdOutWrittenTo:
        $ref: '#/definitions/ContainerStdOutWrittenToEvent'
      opEnded:
        $ref: '#/definitions/OpEndedEvent'
      opStarted:
        $ref: '#/definitions/OpStartedEvent'
      opEncounteredError:
        $ref: '#/definitions/OpEncounteredErrorEvent'
  ContainerExitedEvent:
    type: object
    properties:
      containerRef:
        type: string
      exitCode:
        type: integer
      opGraphId:
        type: string
      containerId:
        type: string
      opRef:
        type: string
  ContainerStartedEvent:
    type: object
    properties:
      containerRef:
        type: string
      opGraphId:
        type: string
      containerId:
        type: string
      opRef:
        type: string
  ContainerStdErrWrittenToEvent:
    type: object
    properties:
      containerRef:
        type: string
      data:
        type: string
        format: binary
      opGraphId:
        type: string
      containerId:
        type: string
      opRef:
        type: string
  ContainerStdOutWrittenToEvent:
    type: object
    properties:
      containerRef:
        type: string
      data:
        type: string
        format: binary
      opGraphId:
        type: string
      containerId:
        type: string
      opRef:
        type: string
  OpEncounteredErrorEvent:
    type: object
    properties:
      opGraphId:
        type: string
      msg:
        type: string
      opId:
        type: string
      opRef:
        type: string
  OpEndedEvent:
    type: object
    properties:
      opGraphId:
        type: string
      opId:
        type: string
      opRef:
        type: string
      outcome:
        enum: [ SUCCEEDED, FAILED, KILLED]
        type: string
  OpStartedEvent:
    type: object
    properties:
      opGraphId:
        type: string
      opId:
        type: string
      opRef:
        type: string
  OpRunArg:
    title: OpRunArg
    description: An arg to be provided to the op
    type: object
    required:
      - name
      - value
    properties:
      name:
        type: string
      value:
        type: string
