approve_by_comment: true
approve_regex: ^[Aa]pproved
reject_regex: ^[Rr]ejected
reset_on_push: true
author_approval: ignored
reviewers:
  teams:
    - sdk-golang-maintainers
  name: default
  required: 1
