language: generic
sudo: required
before_script:
- sudo apt-get remove --purge docker-engine
- curl -fsSL https://get.docker.com/ | sh
- curl -L https://bin.equinox.io/c/4fmGop7rntx/opctl-beta-linux-amd64.tgz | sudo tar -xzv -C /usr/local/bin
services:
- docker
script:
- opctl run -a srcDir=$(pwd) -a gitBranch=$TRAVIS_BRANCH -a gitCommit=$TRAVIS_COMMIT build
