version: "2"
services:
  push-docker-image:
    extends:
      file: ../.common/docker-compose.yml
      service: docker
    entrypoint: .dev-op-spec/ops/push-docker-image/entrypoint.sh
    environment:
      - DOCKER_EMAIL
      - DOCKER_PASSWORD
      - DOCKER_USERNAME
