version: "2"
services:
  push-docker-image:
    extends:
      file: ../.common/docker-compose.yml
      service: working_dir
    image: docker:1.10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: .dev-op-spec/ops/push-docker-image/entrypoint.sh
    environment:
      - DOCKER_REPO_NAME=devopspec/engine
      - DOCKER_EMAIL
      - DOCKER_PASSWORD
      - DOCKER_USERNAME