version: "2"
services:
  publish-coverage:
    extends:
      service: go
      file: ../.common/docker-compose.yml
    environment:
      - CODECOV_TOKEN=5f64e6aa-5117-410b-aceb-3188c58e4a18
      - GIT_BRANCH
    entrypoint:
      - sh
      - -ce
      - |
        curl -s https://codecov.io/bash | bash -s
    network_mode: host
