version: "2"
services:
  publish-coverage:
    extends:
      service: go
      file: ../.common/docker-compose.yml
    environment:
      - CODECOV_TOKEN=b432a3b8-8220-4c1d-bcee-db76e68d0128
      - GIT_BRANCH
    entrypoint: |
      sh -ce "
        ### GENERATE AGGREGATE COVERAGE PROFILE
        find . -name '*.coverprofile' | xargs cat > coverage.txt

        ### STRIP FAKES
        sed -i '/fake/d' coverage.txt

        ### UPLOAD
        curl -s https://codecov.io/bash | bash -s
      "
    network_mode: host
