name: build-image
description: Builds a docker image
inputs:
  - string: { name: IMAGE_REF, description: 'Docker image reference. pseudo regex: "((registry/)?namespace/)?repo(:tag)?)"' }
  - dir: { name: BUILD_CONTEXT }
  - socket: { name: DOCKERD_SOCKET }
run:
  container:
    cmd: [ docker, build, -t, $(IMAGE_REF), . ]
    dirs:
      /opt/app: { bind: BUILD_CONTEXT }
    image: docker:1.13
    sockets:
      /var/run/docker.sock: { bind: DOCKERD_SOCKET }
    workDir: /opt/app
