name: build-image
description: Builds a docker image
inputs:
  - string: { name: IMAGE_REF, description: 'Docker image reference. pseudo regex: "((registry/)?namespace/)?repo(:tag)?)"' }
  - dir: { name: BUILD_CONTEXT }
run:
  container:
    cmd:
      - sh
      - -c
      - |
        # start dockerd
        dockerd &>/dev/null &
        # build image
        docker build -t $(IMAGE_REF) .
    fs:
      - { bind: BUILD_CONTEXT, path: /opt/app }
    image: docker:1.12-dind
    workDir: /opt/app
