name: build-image
description: Builds a docker image
inputs:
  build_context: { dir:, description: context to use for docker build }
  dockerd_socket: { socket:, description: socket for a docker daemon }
  image_ref: { string:, description: docker image reference }
run:
  container:
    cmd: [ docker, build, -t, $(image_ref), . ]
    dirs:
      /opt/app: { bind: build_context }
    image: docker:1.13
    sockets:
      /var/run/docker.sock: { bind: dockerd_socket }
    workDir: /opt/app
