name: build-image
description: Builds the docker image
inputs:
  - string: { name: IMAGE_REF, description: Docker image reference, pattern: '((registry/)?namespace/)?repo(:tag)?)' }
  - dir: { name: BUILD_CONTEXT }
run:
  container:
    cmd: docker build -t $IMAGE_REF .
    fs:
      - { bind: BUILD_CONTEXT, path: /opt/app }
    image: docker:1.12.0
    workDir: /opt/app
