name: build-image
description: Builds a docker image
inputs:
  buildContext:
    dir:
      default: .
      description: context to use for docker build
  dockerSocket:
    socket:
      description: socket for docker daemon
  imageRef:
    string:
      constraints: { format: docker-image-ref }
run:
  container:
    cmd: [ docker, build, -t, $(imageRef), . ]
    dirs:
      /opt/app: buildContext
    image: docker:1.13
    sockets:
      /var/run/docker.sock: dockerSocket
    workDir: /opt/app
