name: build-image
description: Builds a docker image
inputs:
  - string: { name: IMAGE_REF, description: 'Docker image reference. pseudo regex: "((registry/)?namespace/)?repo(:tag)?)"' }
  - dir: { name: BUILD_CONTEXT }
run:
  container:
    cmd:
      - sh
      - -c
      - |
        # start dockerd
        dockerd &>/dev/null &

        echo sleeping for 2 sec to allow dockerd enough time to startup
        sleep 2

        # build image
        docker build -t $(IMAGE_REF) .
    dirs:
      /opt/app: { bind: BUILD_CONTEXT }
    image: docker:1.12-dind
    workDir: /opt/app
