name: build-login-push
description: Builds an image, logs in to a docker registry, and pushes the image to it.
inputs:
  build_context: { dir:, description: context to use for docker build }
  docker_password: { string:, description: password for docker registry, isSecret: true }
  dockerd_socket: { socket:, description: socket for a docker daemon }
  docker_username: { string:, description: username for docker registry, isSecret: true }
  image_ref: { string:, description: docker image reference }
run:
  serial:
    - op: { ref: build-image, inputs: { build_context, dockerd_socket, image_ref } }
    - op: { ref: login, inputs: { dockerd_socket, docker_password, docker_username }, outputs: { docker_config } }
    - op: { ref: push-image, inputs: { docker_config, dockerd_socket, image_ref } }
