name: build-login-push
description: Builds an image, logs in to a docker registry, and pushes the image to it.
inputs:
  buildContext:
    dir:
      description: context to use for docker build
  dockerPassword:
    string:
      constraints: { minLength: 1 }
      isSecret: true
  dockerSocket:
    socket:
      description: socket for docker daemon
  dockerUsername:
    string:
      constraints: { format: email }
      isSecret: true
  imageRef:
    string:
      constraints: { format: docker-image-ref }
run:
  serial:
    - op: { ref: build-image, inputs: { buildContext, dockerSocket, imageRef } }
    - op: { ref: login, inputs: { dockerSocket, dockerPassword, dockerUsername }, outputs: { dockerConfig } }
    - op: { ref: push-image, inputs: { dockerConfig, dockerSocket, imageRef } }
