version: "2"
services:
  working_dir:
    image: scratch
    volumes:
      - ../../../:/golang/src/github.com/dev-op-spec/engine
    working_dir: /golang/src/github.com/dev-op-spec/engine
  go:
    build: ./
    extends:
      service: working_dir
    environment:
      - GOPATH=/golang
      - GOARCH=amd64
      - CGO_ENABLED=0
      - GOOS=linux
  docker:
    image: docker:1.10
    extends:
      file: ../.common/docker-compose.yml
      service: working_dir
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_REPO_NAME=devopspec/engine
