swagger: '2.0'
info:
  version: '0.1.4'
  title: Node API
consumes:
  - application/json
produces:
  - application/json
  - text/plain
paths:
  /events/stream:
    get:
      summary: Get an event stream
      description: |
        The connection will be upgraded to use the websocket protocol.
      parameters:
        - name: filter
          in: query
          description: |
            A json encoded object supporting the following:

            |attribute|type|description|
            |--|--|--|
            |rootOpIds|array of strings|allows filtering events to those w/ rootOpId matching one of those provided|
            |since|datetime|allows filtering events to those occurring on/after the provided datetime|

          required: false
          type: string
          format: json
      tags: [ events ]
      responses:
        '101':
          description: Switching Protocols
          headers:
            Upgrade:
              type: string
              enum:
                - websocket
            Connection:
              type: string
              enum:
                - Upgrade
          schema:
            type: array
            items:
              $ref: '#/definitions/Event'
        '400':
          description: Bad Request
          schema:
            type: string
  /liveness:
    get:
      summary: Get liveness of node
      tags: [ liveness ]
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /ops/starts:
    post:
      summary: Starts an op
      tags: [ ops ]
      parameters:
        - name: body
          in: body
          required: true
          schema:
            required: [ pkg ]
            properties:
              args:
                description: arguments to pass to the op as inputs
                type: array
                items:
                  $ref: '#/definitions/OpArg'
              pkg:
                required: [ ref ]
                properties:
                  ref:
                    type: string
                    description: a pkg reference in the form of a URL or absolute file path
                  pullAuth:
                    description: username & password to use for pullAuth
                    required: [ username, password ]
                    properties:
                      username:
                        type: string
                      password:
                        type: string
      responses:
        '201':
          description: Created
          schema:
            description: The id of the [started] op
            type: string
        '400':
          description: Bad Request
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
  /ops/kills:
    post:
      summary: Kills an op
      tags: [ ops ]
      parameters:
        - name: body
          in: body
          required: true
          schema:
            required: [ opRunId ]
            properties:
              opRunId:
                type: string
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
definitions:
  Event:
    properties:
      timestamp:
        type: string
        format: dateTime
      # @TODO: use oneOf as soon as OpenAPI v3 is released
      containerExited:
        $ref: '#/definitions/ContainerExitedEvent'
      containerStarted:
        $ref: '#/definitions/ContainerStartedEvent'
      containerStdErrWrittenTo:
        $ref: '#/definitions/ContainerStdErrWrittenToEvent'
      containerStdOutWrittenTo:
        $ref: '#/definitions/ContainerStdOutWrittenToEvent'
      opEnded:
        $ref: '#/definitions/OpEndedEvent'
      opStarted:
        $ref: '#/definitions/OpStartedEvent'
      opEncounteredError:
        $ref: '#/definitions/OpEncounteredErrorEvent'
  ContainerExitedEvent:
    properties:
      containerRef:
        type: string
      exitCode:
        type: integer
      rootOpId:
        type: string
      containerId:
        type: string
      pkgRef:
        type: string
  ContainerStartedEvent:
    properties:
      containerRef:
        type: string
      rootOpId:
        type: string
      containerId:
        type: string
      pkgRef:
        type: string
  ContainerStdErrWrittenToEvent:
    properties:
      containerRef:
        type: string
      data:
        type: string
        format: binary
      rootOpId:
        type: string
      containerId:
        type: string
      pkgRef:
        type: string
  ContainerStdOutWrittenToEvent:
    properties:
      containerRef:
        type: string
      data:
        type: string
        format: binary
      rootOpId:
        type: string
      containerId:
        type: string
      pkgRef:
        type: string
  OpEncounteredErrorEvent:
    properties:
      rootOpId:
        type: string
      msg:
        type: string
      opId:
        type: string
      pkgRef:
        type: string
  OpEndedEvent:
    properties:
      rootOpId:
        type: string
      opId:
        type: string
      pkgRef:
        type: string
      outcome:
        enum: [ SUCCEEDED, FAILED, KILLED]
        type: string
  OpStartedEvent:
    properties:
      rootOpId:
        type: string
      opId:
        type: string
      pkgRef:
        type: string
  OpArg:
    description: An arg to be provided to the op
    type: object
    # @TODO: use patternProperties if/when OpenAPI spec supports it
