name: push-image
description: Pushes a local image to a registry
inputs:
  - string: { name: IMAGE_REF, description: 'Docker image reference (regex: `((registry/)?namespace/)?repo(:tag)?`)' }
  - file: { name: DOCKER_CONFIG, description: Docker config.json file, isSecret: true }
  - socket: { name: DOCKERD_SOCKET }
run:
  container:
    cmd: [ docker, push, $(IMAGE_REF) ]
    files:
      /root/.docker/config.json: { bind: DOCKER_CONFIG }
    image: docker:1.13
    sockets:
      /var/run/docker.sock: { bind: DOCKERD_SOCKET }
