name: push-image
description: Pushes a local image to a registry
inputs:
  - { name: DOCKER_PASSWORD, description: Password for docker registry, isSecret: true }
  - { name: DOCKER_USERNAME, description: Username for docker registry, isSecret: true }
  - { name: IMAGE_REF, description: 'Docker image reference (regex: `((registry/)?namespace/)?repo(:tag)?`)' }
