name: push-image
description: Pushes a local image to a registry
inputs:
  dockerSocket:
    socket:
      description: socket for docker daemon
  dockerConfig:
    file:
      description: config for docker CLI
      isSecret: true
  imageRef:
    string:
      constraints: { format: docker-image-ref }
run:
  container:
    cmd: [ docker, push, $(imageRef) ]
    files:
      /root/.docker/config.json: dockerConfig
    image: { ref: 'docker:1.13' }
    sockets:
      /var/run/docker.sock: dockerSocket
