version: "2"
services:
  push-docker-image:
    extends:
      file: ../.common/docker-compose.yml
      service: docker
    entrypoint: .opspec/push-docker-image/entrypoint.sh
    environment:
      - DOCKER_REPO_NAME=opctl/engine
      - DOCKER_PASSWORD
      - DOCKER_USERNAME
