name: login
description: Logs in to a docker registry
inputs:
  - string: { name: DOCKER_PASSWORD, description: Password for docker registry, isSecret: true}
  - string: { name: DOCKER_USERNAME, description: Username for docker registry, isSecret: true}
outputs:
  - file: { name: DOCKER_CONFIG, description: Can be used for caching, isSecret: true}
run:
  container:
    cmd:
      - sh
      - -c
      - |
        # start dockerd
        dockerd &>/dev/null &

        echo sleeping for 2 sec to allow dockerd enough time to startup
        sleep 2

        docker login -u "$(DOCKER_USERNAME)" -p "$(DOCKER_PASSWORD)"
    fs:
      - { bind: DOCKER_CONFIG, path: /root/.docker }
    image: docker:1.12-dind
