name: login
description: Logs in to a docker registry
inputs:
  docker_password: { string:, description: password for docker registry, isSecret: true }
  dockerd_socket: { socket:, description: socket for a docker daemon }
  docker_username: { string:, description: username for docker registry, isSecret: true }
outputs:
  docker_config: { file:, description: config for docker CLI, isSecret: true }
run:
  container:
    cmd: [ docker, login, -u, $(docker_username), -p, $(docker_password) ]
    files:
      /root/.docker/config.json: { bind: docker_config }
    image: docker:1.13
    sockets:
      /var/run/docker.sock: { bind: dockerd_socket }
