description: Deploys artifacts from build
name: deploy
inputs:
  srcDir:
    dir:
      default: .
      description: directory containing the projects source code
  AWS_ACCESS_KEY_ID:
    string:
      constraints: { minLength: 20 }
      description: access key for AWS
  AWS_SECRET_ACCESS_KEY:
    string:
      constraints: { minLength: 20 }
      description: secret access key for AWS
      isSecret: true
  version:
    string:
      constraints: { format: semver }
      description: version of the spec being deployed
run:
  parallel:
    - op:
        pkg: { ref: spec/deploy }
        inputs:
          srcDir:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          version:
    - op:
        pkg: { ref: website/deploy }
        inputs:
          srcDir:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
