description: Runs all ops necessary to build & deploy the spec
name: deploy
inputs:
  srcDir:
    dir:
      default: .
      description: dir containing the doc source
  AWS_ACCESS_KEY_ID:
    string:
      constraints: { minLength: 20 }
      description: access key for AWS
  AWS_SECRET_ACCESS_KEY:
    string:
      constraints: { minLength: 20 }
      description: secret access key for AWS
      isSecret: true
  version:
    string:
      constraints: { format: semver }
      description: version of the spec being deployed
run:
  serial:
    - op:
        pkg: { ref: build }
        inputs: { srcDir, version }
        outputs: { srcDir }
    - container:
        cmd:
          - sh
          - -ce
          - |
            echo "installing deps"
            pip install awscli

            echo "deploying to /"
            aws s3 sync . s3://opspec.io --delete

            echo "deploying to /$(version)"
            aws s3 sync latest s3://opspec.io/$(version) --delete
        dirs:
          /src: srcDir
        envVars:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          AWS_DEFAULT_REGION: us-west-2
        image: { ref: 'python:2.7' }
        workDir: /src/build
