description: Runs all ops necessary to deploy docs
name: deploy-docs
inputs:
  srcDir:
    dir:
      default: .
      description: dir containing the doc source
  awsAccessKeyId:
    string:
      constraints: { minLength: 20 }
      description: access key for AWS
  awsSecretAccessKey:
    string:
      constraints: { minLength: 20 }
      description: secret access key for AWS
      isSecret: true
  version:
    string:
      constraints: { format: semver }
      description: version of the spec being deployed
run:
  serial:
    - op: { ref: clean, inputs: { srcDir }, outputs: { srcDir }}
    - op: { ref: compile-gitbook, inputs: { srcDir }, outputs: { srcDir }}
    - container:
        cmd:
          - sh
          - -ce
          - |
            echo "installing deps"
            pip install awscli

            echo "deploying spec"
            aws s3 sync . s3://opspec.io/spec --delete

            echo "deploying versioned schema"
            aws s3 sync latest/schema s3://opspec.io/spec/$(version)/schema --delete
        dirs:
          /src: srcDir
        envVars:
          AWS_ACCESS_KEY_ID: $(awsAccessKeyId)
          AWS_SECRET_ACCESS_KEY: $(awsSecretAccessKey)
          AWS_DEFAULT_REGION: us-west-2
        image: { ref: 'python:2.7' }
        workDir: /src/_book
