description: Runs all deploy ops
name: deploy
inputs:
  - { name: AWS_ACCESS_KEY_ID, description: Access key for AWS, isSecret: true }
  - { name: AWS_SECRET_ACCESS_KEY, description: Secret access key for AWS, isSecret: true }
  - { name: SPEC_VERSION, description: Version of the spec being deploy }
