name: login
description: Logs in to a docker registry
inputs:
  dockerPassword:
    string:
      constraints: { minLength: 1 }
      isSecret: true
  dockerSocket:
    socket:
      description: socket for docker daemon
  dockerUsername:
    string:
      constraints: { format: email }
      isSecret: true
outputs:
  dockerConfig:
    file:
      description: config for docker CLI
      isSecret: true
run:
  container:
    cmd: [ docker, login, -u, $(dockerUsername), -p, $(dockerPassword) ]
    files:
      /root/.docker/config.json: dockerConfig
    image: { ref: 'docker:1.13' }
    sockets:
      /var/run/docker.sock: dockerSocket
