version: "2"
services:
  release-publish:
    extends:
      service: go
      file: ../.common/docker-compose.yml
    entrypoint:
      - sh
      - -ce
      - |
        ### DETERMINE CHANNEL
        if echo "$VERSION" | grep -Eq "*.-beta\.*."; then
          channel=beta
        else
          channel=stable
        fi

        ### RELEASE
        equinox release \
        --channel="$${channel}" \
        --version="${VERSION}" \
        --platforms="darwin_amd64 linux_amd64 windows_amd64" \
        --app="app_kNrDsPk2bis" \
        --token="${EQUINOX_TOKEN}" \
        -- -a github.com/opspec-io/opctl/cli
    environment:
    - EQUINOX_SIGNING_KEY
    - CGO_ENABLED=0
    network_mode: host
