version: "2"
services:
  working_dir:
    image: scratch
    volumes:
      - ../../:/go/src/github.com/opspec-io/opctl
    working_dir: /go/src/github.com/opspec-io/opctl
  go:
    build: .
    extends:
      service: working_dir
