version: "2"
services:
  working_dir:
    image: scratch
    volumes:
      - ../../:/go/src/github.com/opspec-io/engine
    working_dir: /go/src/github.com/opspec-io/engine
  go:
    build: .
    extends:
      service: working_dir
    environment:
      - GOARCH=amd64
      - GOOS=linux
  docker:
    image: docker:1.12.1
    extends:
      file: ../.common/docker-compose.yml
      service: working_dir
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
