description: Runs all ops necessary to deploy the website
name: website/deploy
inputs:
  srcDir:
    dir:
      default: .
      description: directory containing the projects source code
  AWS_ACCESS_KEY_ID:
    string:
      constraints: { minLength: 20 }
      description: access key for AWS
  AWS_SECRET_ACCESS_KEY:
    string:
      constraints: { minLength: 20 }
      description: secret access key for AWS
      isSecret: true
run:
  container:
    cmd:
      - sh
      - -ce
      - |
        echo "installing deps"
        pip install awscli

        echo "deploying to /"
        aws s3 sync . s3://opspec.io
    dirs:
      /src: $(srcDir)
    envVars:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION: us-west-2
    image: { ref: 'python:2.7' }
    workDir: /src/build
